# Generated by Django 6.0.1 on 2026-02-02 21:13

import django.db.models.deletion
import weddin_invitation_app.models.guests
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование свадьбы')),
            ],
            options={
                'verbose_name': 'Свадьба',
                'verbose_name_plural': 'Свадьбы',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_token', models.CharField(blank=True, default=weddin_invitation_app.models.guests.generate_token, max_length=128, verbose_name='Уникальный токен')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=128, verbose_name='Фамилия')),
                ('invitation_official_event', models.BooleanField(blank=True, default=True, verbose_name='Приглашение на официальное мероприятие')),
                ('invitiation_none_official_event', models.BooleanField(blank=True, default=True, verbose_name='Приглашение на неофициальное мероприятие')),
                ('drinks', models.TextField(blank=True, null=True, verbose_name='Предпочтение по напиткам')),
                ('music', models.TextField(blank=True, null=True, verbose_name='Предпочтение по музыке')),
                ('finish_invitiation', models.BooleanField(blank=True, default=False, verbose_name='Закончил заполнение приглшения')),
                ('presence_on_official_event', models.BooleanField(blank=True, default=False, verbose_name='Присуствие на оф мероприятии')),
                ('presence_on_none_official_event', models.BooleanField(blank=True, default=False, verbose_name='Присутсвие на не оф мероприятии')),
                ('wedding', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='weddin_invitation_app.wedding', verbose_name='Свадьба')),
            ],
            options={
                'verbose_name': 'Приглашение гостя',
                'verbose_name_plural': 'Приглашение гостей',
            },
        ),
        migrations.CreateModel(
            name='WeddingNoneOficialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и вермя мероприятия')),
                ('address', models.TextField(verbose_name='Адрес мероприятия')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_oficial_event', to='weddin_invitation_app.wedding', verbose_name='Свадьба')),
            ],
            options={
                'verbose_name': 'Не официальное мероприятие',
                'verbose_name_plural': 'Не официальные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='WeddingOficialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время мероприятия')),
                ('address', models.TextField(verbose_name='Адрес мероприятия')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oficial_event', to='weddin_invitation_app.wedding', verbose_name='Свадьба')),
            ],
            options={
                'verbose_name': 'Официальное мероприятие',
                'verbose_name_plural': 'Официальные мероприятия',
            },
        ),
    ]
