# Generated by Django 6.0.1 on 2026-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddin_invitation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='permission_plus_one',
            field=models.BooleanField(blank=True, default=False, verbose_name='Возможность +1 гость'),
        ),
        migrations.AddField(
            model_name='guest',
            name='will_plus_one',
            field=models.BooleanField(blank=True, default=False, verbose_name='Будет +1 гость'),
        ),
    ]
