# Generated by Django 6.0.1 on 2026-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddin_invitation_app', '0002_guest_permission_plus_one_guest_will_plus_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='female',
            field=models.BooleanField(blank=True, default=False, verbose_name='Женщина'),
        ),
        migrations.AddField(
            model_name='guest',
            name='male',
            field=models.BooleanField(blank=True, default=False, verbose_name='Мужчина'),
        ),
    ]
