# Generated by Django 6.0.1 on 2026-02-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddin_invitation_app', '0003_guest_female_guest_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingnoneoficialevent',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания мероприятия'),
        ),
        migrations.AddField(
            model_name='weddingoficialevent',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания мероприятия'),
        ),
    ]
