version: '3.7'

services:
  database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psadmin -d wedding_invitation"]
      interval: 5s
      timeout: 5s
      retries: 5

    container_name: wedding-invitation-database
    restart: always
    ports:
      - "5432:5432"

    env_file:
      - ./dev-env/database.env

    image: postgres:17.6-alpine

    volumes:
      - ./database/data:/var/lib/postgresql/data

    networks:
     - wedding-invitation-network

  django-app:
    build:
      context: ./django-project
      dockerfile: dockerfile
    container_name: wedding-invitation-django-app
    restart: always
    ports:
      - "8000:8000"

    env_file:
      - ./dev-env/backend.env

    volumes:
      - ./staticfiles/:/home/django-app/staticfiles

    depends_on:
      - database
      
    networks:
     - wedding-invitation-network

  nginx:
    build: './nginx'
    restart: always
    ports:
      - 80:80

    volumes:
      - ./staticfiles/:/home/app/djangoApp
    depends_on:
      - django-app
    networks:
     - wedding-invitation-network


networks:
  wedding-invitation-network:
    driver: bridge